sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t mtnfranke/rpi-photo-frame .
# test image
- docker run mtnfranke/rpi-photo-frame /bin/bash
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG="latest"
    docker tag mtnfranke/rpi-photo-frame mtnfranke/rpi-photo-frame:$TAG
    docker push mtnfranke/rpi-photo-frame:$TAG
    docker push mtnfranke/rpi-photo-frame
  fi
